# Cloudflare Pages configuration for Weather Dashboard

name = "professional-weather-dashboard"
compatibility_date = "2025-09-09"

# Pages specific configuration
[pages]
build_command = "npm run build"
pages_build_output_dir = "dist"

[build]
command = "npm run build"
upload.format = "service-worker"

[site]
bucket = "./dist"

[build.environment]
NODE_VERSION = "18"

[env.production]
name = "professional-weather-dashboard"
workers_dev = false

[env.staging]
name = "professional-weather-dashboard-staging"
workers_dev = true

# Environment variables reference (don't put actual values here)
# These will be set in the Cloudflare dashboard
