# Cloudflare Pages configuration for Weather Dashboard

name = "professional-weather-dashboard"
type = "frontend"

[build]
command = "npm run build"
output = "dist"
publish = "dist"

[build.environment]
NODE_VERSION = "18"

[site]
bucket = "./dist"
entry-point = "."

[env.production]
name = "professional-weather-dashboard"
workers_dev = false
routes = [
  { pattern = "*weatherdashboard.yourdomain.com/*", zone_id = "your_zone_id" }
]

[env.staging]
name = "professional-weather-dashboard-staging"
workers_dev = true

# Environment variables reference (don't put actual values here)
# These will be set in the Cloudflare dashboard
# [vars]
# API_URL = "value"
